version: '3'

services:
  mox:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # The `volumes` and `command` mounts the current directory in the docker
    # container and overwrites the CMD from Dockerfile. With this gunicorn
    # reloads on file changes. This is very useful when developing oio_rest.
    volumes:
      - .:/code
      - ./user-settings.toml:/user-settings.toml
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:8080", "oio_rest.app:app"]
    ports:
      - "8080:8080"
    env_file:
      - docker/db.env
    depends_on:
      - mox-db

  mox-db:
    image: postgres:9.6
    env_file:
      - docker/db.env
    volumes:
      - ./docker/postgres-initdb.d/:/docker-entrypoint-initdb.d
      #- postgres-initdb.d:/docker-entrypoint-initdb.d


  # The following service is to copy the scripts needed to initialize the
  # database with user and extentions to a volume. It is not needed when the
  # volume `./docker/postgres-initdb.d/:/docker-entrypoint-initdb.d` is bound in
  # mox-db above.
  mox-cp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: root
    entrypoint: []
    command: ["cp", "-r", "/code/docker/postgres-initdb.d/.", "/postgres-initdb.d"]
    volumes:
      - postgres-initdb.d:/postgres-initdb.d

volumes:
  postgres-initdb.d:
