version: '3'

services:
  mox:
    build: .
    # The `volumes` and `command` mounts the current directory in the docker
    # container and overwrites the CMD from Dockerfile. With this gunicorn
    # reloads on file changes. This is very useful when developing oio_rest.
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:5000", "oio_rest.app:app"]
    ports:
      - "5000:5000"
    env_file:
      - db.env
    environment:
      - DB_HOST=mox-db
    depends_on:
      - mox-db

  mox-db:
    image: postgres:9.6
    env_file:
      - db.env
