version: '3'

services:
  mox:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # The `volumes` and `command` mounts the current directory in the docker
    # container and overwrites the CMD from Dockerfile. With this gunicorn
    # reloads on file changes. This is very useful when developing oio_rest.
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "-b", "0.0.0.0:8080", "oio_rest.app:app"]
    ports:
      - "8080:8080"
    env_file:
      - docker/db.env
    environment:
      - DB_HOST=mox-db
    depends_on:
      - mox-db

  mox-db:
    image: postgres:9.6
    env_file:
      - docker/db.env
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/01-init-db.sh
      - ./docker/create-extensions.sh:/docker-entrypoint-initdb.d/02-create-extensions.sh
